### PR TITLE
Adding Alvaro changes

### PR DESCRIPTION
**Pull request by ramygad**
Hi here is the changes that Alvaro added

### CODE REVIEW

**Comment by jbreitbart** [comment]
Hi

the diff is really strange. Can you provide a clean diff so that we can continue to track changes in the git?

I'll close this pull request. Just open a new one. I hope that is ok for you.

**Comment by ramygad** [comment]
Alvaro asks: What changes you don't like?

**Comment by jbreitbart** [comment]
The diff (see e.g. https://github.com/fast-project/communication-spec/pull/5/files ) includes almost the whole file. Did you really need to change the whole file?

**Comment by stlankes** [comment]
The diff shows that you changed every line. This is definitely not true. Maybe you changed the file encoding and git isn't able to detect the "real" changes. Consequently, a code review isn't possible, which is one reason of a pull request.

**Comment by ramygad** [comment]
Dear Jens,
Alvaro asks me to put this file on github on behave of him.
Now I understand the problem.
I will forward your  answer to him.

Best regards,
Ramy

**Comment by stlankes** [comment]
I just notice that Alvaro remove all markdown elements that should be the reason for the strange diff.

**Pull request closed without merging**
